[package]
name = "fuseio"
version = "0.1.0"
edition = "2024"

[dependencies]
aligned-vec = "0.6.4"
arrayvec = "0.7.6"
async-bounds = "0.1.0"
atomic-waker = "1.1.2"
bitflags = { version = "2.11.0", features = ["bytemuck"] }
bytemuck = { version = "1.25.0", features = ["derive"] }
compio = { version = "0.19.2", features = ["async-fd", "io"] }
crossbeam-utils = { version = "0.8.21", default-features = false }
crossfire = "3.1.7"
either = "1.15.0"
futures-util = { version = "0.3.32", default-features = false, features = ["io"] }
log = "0.4.29"
memchr = "2.8.0"
nix = { version = "0.31.2", features = ["user", "process", "fs", "ioctl", "poll"] }
page_size = "0.6.0"
scc = "3.7.0"
