[package]
name = "fuseio"
version = "0.1.0"
edition = "2024"

[dependencies]
aligned-vec = "0.6"
arrayvec = "0.7"
atomic-waker = "1"
bitflags = "2"
bytemuck = "1"
compio = { version = "0.19", features = ["async-fd", "io"] }
crossbeam-utils = { version = "0.8", default-features = false }
crossfire = "3"
either = "1"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
log = "0.4"
memchr = "2"
nix = { version = "0.31", features = ["user", "process", "fs", "ioctl", "poll"] }
page_size = "0.6"
unsync = "0.2"
